### ISSUE TITLE
Misleading information about accessing user profile

### ISSUE THREAD

**Issue by ahendy** [OfficeDev/Microsoft-teams-docs#101]
https://github.com/OfficeDev/Microsoft-teams-docs/blob/master/teams/botsconversation.md#constructing-mentions

> Include @username in the message text. Note, at this time because we do not provide an API to return profile information, you can either obtain this value from a received message or from an external lookup, **e.g. Azure ActiveDirectory**

Using Microsoft Graph API would require having an  AAD UserId which is not the same as a MS Teams UserId. I believe leaving this example is then misleading to readers and am currently unaware of any other lookup which could be done.

**Comment by RichMoeMSFT** [comment]
Understood, to clarify, what is meant is that you'd have to federate the Teams identity with some other source.  E.g. map an auth that you initiate back to the Teams id.   Thanks for the feedback, I'll wordsmith.

**Comment by ahendy** [comment]
Yes this is correct
