### ISSUE TITLE
Meetnow is not honoring company proxy and therefore doesn't work

### ISSUE THREAD

**Issue by adameska** [OfficeDev/Microsoft-teams-docs#106]
Thank you for helping us to improve the Microsoft Teams developer documentation.
 
Article:

Issue: We are trying to replace Skype with this tool as skype crashes a lot for us and the only thing preventing us from doing so is the meetnow functionality not working for our company, according to wireshark it seems it's ignoring system proxy settings!

**Comment by SheriEllisMSFT** [comment]
@adameska - Hi Dave, apologies we missed your question. So to confirm: you are attempting to initiate MeetNow inside Teams in a channel with the video button? or are you doing this in code somehow? It seems to me  like a support issue. Recommend that you contact [Support](https://support.office.com/en-us/teams?ui=en-US&rs=en-US&ad=US). Would love to know what you find! Thanks for posting.
