### ISSUE TITLE
CardAction Type OpenUrl doesn't work when "tap" on a HeroCard

### ISSUE THREAD

**Issue by ahendy** [OfficeDev/Microsoft-teams-docs#114]
Using the bot framework I build a herocard. On the card image I put a tap Action to open a URL EG: new CardAction(type: ActionTypes.OpenUrl, value:  www.myurl.com). On the herocard I also put a tap action to open a URL. On desktop client nothing happens, on web client a new tab is opened but not the URL specified, and on iOS nothing happens.

**Comment by siduppal** [comment]
@ahendy  can you share the exact JSON your bot is sending?

**Comment by RichMoeMSFT** [comment]
@ahendy  Following up on this.  Is this still an active issue?

**Comment by ahendy** [comment]
@RichMoeMSFT not sure. I was interning (Sid was one of my team sponsors) and Sid said a fix was in the pipeline but I don't have access to the code or the bot anymore.
