### ISSUE TITLE
The example scmena in Microsoft Teams manifest schema reference

### ISSUE THREAD

**Issue by jkhlam** [OfficeDev/Microsoft-teams-docs#129]
Article: https://msdn.microsoft.com/en-us/microsoft-teams/schema

Issue: 

In the schema example:
(1) configurableTabs:canUpdateConfig - should be configurableTabs:canUpdateConfiguration
(2) icons:color - please remove the comma at the end of line

**Comment by RichMoeMSFT** [comment]
Updated.  Thanks!
