### ISSUE TITLE
Use old sdks and manifest scheme in createconfigpage.md

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/Microsoft-teams-docs#153]
I found some old sdk version and manifest scheme in this page.
- "configUrl" should be updated to "configurationUrl"
- sample load v0.4 sdk
- "suggestedDisplayName" should be updated to "suggestedTabName"

**Comment by dfederm** [comment]
Assigned to @NT-D since he already has a PR out for it.

Note that the last bullet point is incorrect. `suggestedDisplayName` is the correct field name as per the latest schema.
