### ISSUE TITLE
Does Teams support CardActions in SuggestedActions on messages sent in a Bot?

### ISSUE THREAD

**Issue by weretygr** [OfficeDev/Microsoft-teams-docs#173]
I have created a Bot using the Bot framework but when sending a reply, the suggested actions never appear (though they do in the emulator).  I have tried the OpenUrl and invoke actions but neither of these seem to work.

**Comment by SheriEllisMSFT** [comment]
@weretygr - Hi Wayne! Sorry you're having trouble. Are you using C# or Node? Could you share your botID and your code snippet? You might take a look at our [Get-Started sample](https://github.com/OfficeDev/microsoft-teams-sample-get-started). It has sample code in both C# and Node which use OpenUrl in bot dialogs.

**Comment by RichMoeMSFT** [comment]
Suggested Actions are not supported in Microsoft Teams at the moment.  We'll update the documentation and alert engineering.
