### ISSUE TITLE
Error while reading manifest.json: Error while extracting package: manifest.json not found in the package

### ISSUE THREAD

**Issue by panosVeran** [OfficeDev/Microsoft-teams-docs#185]
when i modify manifest.json (adding the ids needed) file and zip the folder again i try to upload it through sideload a tab or bot it prints the error "Error while reading manifest.json: Error while extracting package: manifest.json not found in the package". what is the problem? i am using visual studio to modify the file so i don't think this  is the problem.

**Comment by RichMoeMSFT** [comment]
The most common cause of this is that when zipping, the manifest ends up in a folder inside the zip.  It must be at the root level of file.  If that's not it, happy to take a look at your zip file.

**Comment by temores** [comment]
I do think that we should update teams' error message to give probable causes, I spent hours trying to find an error on my manifest file.
