### ISSUE TITLE
Fetch Teams List with Bot

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/Microsoft-teams-docs#229]
Article:
Bot APIs (Fetching the list of channels in a team)
Issue: 
I am working on Microsoft Bot Framework and I want to fetch list of Teams in which my Bot is present. I want to fetch teams list before fetching List of Channels using Bot Application.

Followed Link : https://msdn.microsoft.com/en-us/microsoft-teams/botapis

**Comment by RichMoeMSFT** [comment]
There is no way to fetch a list of all teams your bot is in. You receive notification when a bot is added/removed, and you get information on the team when receiving a message. In all cases, you're going to want to cache the team information on your service.
