### ISSUE TITLE
Add note on how to obtain teamId to botapis.md

### ISSUE THREAD

**Issue by billbliss** [OfficeDev/Microsoft-teams-docs#260]
**Article:** botapis.md

**Issue:** In this section: https://msdn.microsoft.com/en-us/microsoft-teams/botapis#fetching-the-team-roster, it talks about the teamId but it's not at all clear how to obtain it. The only way to obtain it is from a message received by the bot from the team context - either from a user message or from the message a bot receives when it's added to the team, as documented here: https://msdn.microsoft.com/en-us/microsoft-teams/botevents#bot-or-user-added-to-a-team. 

A note to this effect would be very useful.

**Comment by billbliss** [comment]
We also need to document what endpoint to use! This isn't explained anywhere. 

For example to retrieve the team roster we say do a GET on `/v3/conversations/{teamId}/members/` but we never say what endpoint to use!

The answer is the serviceUrl but we never say that.

**Comment by majordamage** [comment]
See PR #265. (I debated how best to present the information. Because a reader might jump directly to a specific section, I settled on duplicating the text in both REST sections. YMMV.)

**Comment by majordamage** [comment]
Pushed to live.
