### ISSUE TITLE
Question - Support for Mircosoft Teams Java SDK

### ISSUE THREAD

**Issue by emeraldjava** [OfficeDev/Microsoft-teams-docs#63]
Hi,

I know there is support for C#, javascript and node SDK's for microsoft teams, but are there any plans to support a Java api.

Regards,
Paul O'Connell

**Comment by RichMoeMSFT** [comment]
There are no immediate plans for adding a Java API but I will note your request.

**Comment by jspetrak** [comment]
I had this need yesterday, drafted mine https://github.com/somemove/mstf-teams-kt
Also I have found one existing https://github.com/ajthom90/microsoft-teams-java-api
