### ISSUE TITLE
Question - Bot Framework Support for Teams

### ISSUE THREAD

**Issue by atjohns2** [OfficeDev/Microsoft-teams-docs#65]
Hi,
I'm trying to figure out what is and is not supported in teams currently using the Bot Framework. Essentially I'm trying to answer this question - can I currently build a bot that messages a user or channel directly when an external event takes place and is passed to the bot?

**Comment by RichMoeMSFT** [comment]
This is not currently supported, but we should have more information soon.

**Comment by atjohns2** [comment]
Thanks for the update - I'll keep an eye out.

**Comment by RichMoeMSFT** [comment]
Quick follow up: If the user has already talked to your bot, you have their UID can reply.  Same with a channel - if your bot is added to a team, you get the teamID which is the General Channel id and can send a message to that.   

We still don't have create direct message support but hope to have that in within the next few weeks.
Similarly, querying all channels is not supported quite yet (although you will see channel addition and change events after the bot is added to the team.)

**Comment by RichMoeMSFT** [comment]
@atjohns2  [Direct message support](https://msdn.microsoft.com/en-us/microsoft-teams/botsconversation#direct-message-creation-11) has been added, FYI.
