### ISSUE TITLE
No "Sideload a bot or tab" link

### ISSUE THREAD

**Issue by baole** [OfficeDev/Microsoft-teams-docs#97]
Article: sideload.md

Issue: No "Sideload a bot or tab" link on my bot tab. Please check out my screenshot http://take.ms/tkBzx

Indeed, it shown once, then I click to side load a bot, but nothing was happened. I refreshed the site and the 'sideload a bot or tab' is gone.

**Comment by baole** [comment]
![image](https://cloud.githubusercontent.com/assets/1460168/23944431/218f9108-0973-11e7-9d05-bce572cd23e5.png)

**Comment by baole** [comment]
It works. Thanks @RichMoeMSFT

**Comment by wslyvh** [comment]
Having the same issue. All bot settings (incl. side loading) are turned on from the Admin center.
But it doesn't show up on either web or desktop app. 

I've tried to restart, logout/on again, but doesn't work.
Any other ideas? How did you get it to work @baole ?

![image](https://cloud.githubusercontent.com/assets/25974464/24244472/562f2b74-0fbf-11e7-9489-889ee331fa7d.png)

![image](https://cloud.githubusercontent.com/assets/25974464/24244489/679113e6-0fbf-11e7-9b38-2e57d053c673.png)

**Comment by baole** [comment]
I just followed the guide on the link.

**Comment by wslyvh** [comment]
Reinstalling the Desktop App did the trick for me.
Thanks
